services:
  - type: web
    name: punjab-aqi-weekly-report
    runtime: python
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 600
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.14.3
      - key: AQI_SECRET_KEY
        generateValue: true
